language: node_js
node_js:
  - "node"

services:
  - postgreSQL

cache:
  directories:
    - "node_modules"

env:
  - NODE_ENV=test


before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
  - webpack

script:
  - "npm test"