language: node_js
node_js:
  - "node"

services:
  - postgreSQL

cache:
  directories:
    - "node_modules"

env:
  - NODE_ENV=test

addons:
  postgresql: "9.4"

before_script:
 - psql -c 'create database thesis;' -U postgres 
  - webpack

script:
  - "npm test"