language: node_js
node_js:
  - "node"

services:
  - postgreSQL

cache:
  directories:
    - "node_modules"

env:
  - NODE_ENV=test

before_install: 
 - NODE_ENV=test grunt test

before_script:
  - webpack

script:
  - "npm test"